language: ruby
install: gem install bundler
script: "bundle && bundle exec rake"

rvm:
  - 2.2.2
  - rbx-3.36.0
  - jruby-head
  - rbx-2.5.8
  - ruby-head

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-3.36.0
    - rvm: rbx-2.5.8

notifications:
  irc: "irc.freenode.org#celluloid"

sudo: false
