language: ruby
install: gem install bundler
script: "bundle && bundle exec rake"

rvm:
  - 2.2.2
  - ruby-head
  - jruby-head
  - rubinius-3.36

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rubinius-3.36

notifications:
  irc: "irc.freenode.org#celluloid"

sudo: false
